### PR TITLE
DM-26497:  Update for ts_salobj 6.1 and ts_hexrotcomm 0.10

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by mareuter — COMMENTED** [review]
This looks fine, but I do have two questions:
- The index parameter to amain takes an enum which has two values in it. How does the CSC know which one to be or is this a cross-check mechanism to make sure someone can't specify an index > 2?
- It now looks like the simulation will be done via a --simulate flag. Currently, we do things like -s 1 and -s 2 to differentiate between the types. Does it need to change to something like --simulate --index 1?

**Comment by r-owen** [comment]
When the index parameter to amain receives an IntEnum it adds a required `--index` argument, for which the only choices are the integer values in the enum. It's like `True` in that it requires the user to provide an index, but restricts which values they can provide. This is actually the most common case for indexed SAL components; Test and Script are the only two that can take any non-zero index, the rest have a few specified values. I should have added this feature a long time ago.

Regarding `--simulate`: there are two cases:
* If the CSC has more than one non-zero simulation mode (specified in class constant `valid_simulation_modes`) the argument will accept a value.
* If there is only one valid value (the most common case) then the argument does not accept a value.

Thus your new command would be `--simulate 1` or `--simulate 2`.

**Review by mareuter — APPROVED** [review]
Thanks for the explanations. They make sense to me. This is good to go.

**Comment by r-owen** [comment]
Note: some unit tests are failing because they are not seeing the correct branch of ts_salobj. Apparently the Jenkins file needs an update, but I suggest not doing that until we have settled on a standard unified file.

**Pull request merged**
